export const spotifyFeedUrl = 'https://engineering.atspotify.com/feed'
export const stackOverflowFeedUrl = 'https://stackoverflow.blog/feed'
export const techCrunchFeedUrl = 'https://techcrunch.com/feed'
export const technologyReviewFeedUrl = 'https://www.technologyreview.com/feed'
export const wiredFeedUrl = 'https://www.wired.com/feed/rss'
